apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-demo
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ["git", "clone", "https://github.com/hashimaliii/argocd-demo.git", "/html"]
        volumeMounts:
        - name: html
          mountPath: /html
      volumes:
      - name: html
        emptyDir: {}
